# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "go" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          cache: false
          go-version-file: 'src/go.mod'

      - name: Build
        run: |
          go mod tidy
          go version

      - name: Test
        run: |
          pwd
          go test -v src/math/*
          go test -v src/string/*
          go test -v src/array/*
          go test -v src/list/*
          go test -v src/tree/*
          go test -v src/graph/*
          go test -v src/algo/*
          go test -v src/stack/*
          go test -v src/queue/*
          go test -v src/other/*
